name: Build and Push Polybot

on:
  push:
    branches: [main]
    paths:
      - 'polybot/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Polybot Repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Latest Tag from Docker Hub
        id: get-latest-tag
        run: |
          # Debug: Print raw API response
          RESPONSE=$(curl -s "https://hub.docker.com/v2/repositories/guymeltzer/polybot/tags/?page_size=25")
          echo "Raw Docker Hub response: $RESPONSE"
          
          # Parse tags, handle null or empty results
          LATEST_TAG=$(echo "$RESPONSE" | jq -r '.results[] | .name' 2>/dev/null | \
            grep -E '^1\.0\.[0-9]+$' | \
            sort -V | \
            tail -n 1)
          
          if [ -z "$LATEST_TAG" ]; then
            echo "No valid tag found, starting with 1.0.124"
            LATEST_TAG="1.0.124"
          fi
          
          PATCH_VERSION=$(echo "$LATEST_TAG" | cut -d'.' -f3)
          NEW_PATCH=$((PATCH_VERSION + 1))
          NEW_TAG="1.0.$NEW_PATCH"
          echo "Latest tag: $LATEST_TAG, New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: polybot/
          push: true
          tags: |
            guymeltzer/polybot:${{ steps.get-latest-tag.outputs.NEW_TAG }}
            guymeltzer/polybot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
#
      - name: Checkout Manifests Repo
        uses: actions/checkout@v3
        with:
          repository: guymeltzer/PolybotInfra  # Adjust to your manifests repo
          token: ${{ secrets.GITHUB_TOKEN }}
          path: k8s/Polybot

      - name: Update Deployment with New Tag
        run: |
          sed -i "s|guymeltzer/polybot:.*|guymeltzer/polybot:${{ steps.get-latest-tag.outputs.NEW_TAG }}|" manifests/polybot-deployment.yaml
          cat manifests/polybot-deployment.yaml

      - name: Commit and Push Manifest Changes
        run: |
          cd manifests
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add polybot-deployment.yaml
          git commit -m "Update polybot to ${{ steps.get-latest-tag.outputs.NEW_TAG }}"
          git push